"""add created_at to permits

Revision ID: 84dc704ef74d
Revises: ddbb98f26a51
Create Date: 2026-04-28 13:43:13.660630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dc704ef74d'
down_revision: Union[str, None] = 'ddbb98f26a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permits_to_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permits_to_work', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
