"""initial clean architecture

Revision ID: 8513d5224cc3
Revises: 
Create Date: 2026-04-16 11:39:22.862763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8513d5224cc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'PLANT_MANAGER', 'RELIABILITY_ENGINEER', 'TECHNICIAN', 'OPERATOR', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('department', sa.Enum('FATTY_ACID_PLANT', 'FATTY_ALCOHOL_PLANT', 'REFINERY_PLANT', 'PRODUCTION', 'ELECTRICAL', 'MECHANICAL', 'UTILITIES', 'INSTRUMENTATION', 'WAREHOUSE', 'LOGISTICS', 'CIVIL', 'HR_ADMIN', 'HSSE', 'QA', 'ACCOUNTING', 'LEGAL', name='user_department_enum', create_constraint=True), server_default='MECHANICAL', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_asset', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='wo_priority_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'SUSPENDED', 'CLOSED', name='wo_status_enum', create_constraint=True), nullable=False),
    sa.Column('maintenance_type', sa.Enum('CORRECTIVE', 'PREVENTIVE', 'MODIFICATION', name='wo_type_enum', create_constraint=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_department', sa.Enum('FATTY_ACID_PLANT', 'FATTY_ALCOHOL_PLANT', 'REFINERY_PLANT', 'PRODUCTION', 'ELECTRICAL', 'MECHANICAL', 'UTILITIES', 'INSTRUMENTATION', 'WAREHOUSE', 'LOGISTICS', 'CIVIL', 'HR_ADMIN', 'HSSE', 'QA', 'ACCOUNTING', 'LEGAL', name='wo_assigned_dept_enum', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
