"""add_ptw_table

Revision ID: 878f1b5e293e
Revises: a2899fc7568d
Create Date: 2026-04-20 15:02:49.157224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878f1b5e293e'
down_revision: Union[str, None] = 'a2899fc7568d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permits_to_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('permit_type', sa.Enum('GENERAL', 'HOT_WORK', 'CONFINED_SPACE', 'LOTO', 'LINE_BREAKING', 'WORKING_AT_HEIGHTS', name='permittype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REQUESTED', 'APPROVED', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='permitstatus'), nullable=False),
    sa.Column('requires_loto', sa.Boolean(), nullable=False),
    sa.Column('requires_gas_testing', sa.Boolean(), nullable=False),
    sa.Column('equipment_isolated', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_permits_to_work_approved_by_id_users')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_permits_to_work_requested_by_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_permits_to_work_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits_to_work'))
    )
    with op.batch_alter_table('permits_to_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permits_to_work_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permits_to_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permits_to_work_id'))

    op.drop_table('permits_to_work')
    # ### end Alembic commands ###
