"""add_moc_table

Revision ID: ddbb98f26a51
Revises: 878f1b5e293e
Create Date: 2026-04-21 13:42:52.555784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbb98f26a51'
down_revision: Union[str, None] = '878f1b5e293e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_of_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('MECHANICAL', 'ELECTRICAL', 'INSTRUMENTATION_DCS', 'PROCESS_CHEMICAL', 'PROCEDURE', name='moccategory'), nullable=False),
    sa.Column('stage', sa.Enum('DRAFT', 'ENGINEERING_REVIEW', 'SAFETY_REVIEW', 'APPROVED', 'IMPLEMENTED', 'CLOSED', name='mocstage'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='mocpriority'), nullable=False),
    sa.Column('requires_pid_update', sa.Boolean(), nullable=False),
    sa.Column('requires_dcs_update', sa.Boolean(), nullable=False),
    sa.Column('requires_training', sa.Boolean(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name=op.f('fk_management_of_change_initiator_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_management_of_change_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_management_of_change'))
    )
    with op.batch_alter_table('management_of_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_management_of_change_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_management_of_change_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('management_of_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_management_of_change_title'))
        batch_op.drop_index(batch_op.f('ix_management_of_change_id'))

    op.drop_table('management_of_change')
    # ### end Alembic commands ###
